---
markdown: kramdown
plugins:
  - jekyll-redirect-from
url: https://github.com/googleapis/aip
defaults:
  - scope:
      path: aip
    values:
      areas:
        apps: GSuite
        cloud: Google Cloud Platform
        client-libraries: Client Libraries
      js:
        - /assets/js/proto-syntax.js
  - scope:
      path: README.md
    values:
      exclude_from_search: true
tipue_search:
  include:
    pages: true
