---
markdown: kramdown
plugins:
  - jekyll-redirect-from
url: https://aip.dev
github:
  repository_url: https://github.com/googleapis/aip
include:
  - CONTRIBUTING.md
  - README.md
defaults:
  - scope:
      path: ''
    values:
      areas:
        apps: GSuite
        cloud: Google Cloud Platform
        client-libraries: Client Libraries
      js:
        - /assets/js/proto-syntax.js
  - scope:
      path: aip
    values:
      permalink: none
  - scope:
      path: CONTRIBUTING.md
    values:
      exclude_from_search: true
      permalink: /contributing
  - scope:
      path: index.md
    values:
      exclude_from_search: true
      permalink: /
tipue_search:
  include:
    pages: true
