---
markdown: kramdown
plugins:
  - jekyll-redirect-from
url: https://rhamiltonsf.github.io
baseurl: /aip
github:
  repository_url: https://github.com/rhamiltonsf/aip
include:
  - CONTRIBUTING.md
  - README.md
defaults:
  - scope:
      path: ''
    values:
      areas:
        aog: Actions on Google
        apps: GSuite
        cloud: Google Cloud Platform
        client-libraries: Client Libraries
      js:
        - /assets/js/proto-syntax.js
  - scope:
      path: aip
    values:
      permalink: none
  - scope:
      path: CONTRIBUTING.md
    values:
      exclude_from_search: true
      permalink: /contributing
  - scope:
      path: index.md
    values:
      exclude_from_search: true
      permalink: /
tipue_search:
  include:
    pages: true
